#!/usr/bin/env node
import fs from "node:fs";

const [basePath, currentPath] = process.argv.slice(2);

function parseLcov(filePath) {
	if (!filePath || !fs.existsSync(filePath)) return undefined;

	const totals = {
		lines: { hit: 0, found: 0 },
		functions: { hit: 0, found: 0 },
	};

	for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
		if (line.startsWith("LF:")) totals.lines.found += Number(line.slice(3));
		else if (line.startsWith("LH:")) totals.lines.hit += Number(line.slice(3));
		else if (line.startsWith("FNF:")) totals.functions.found += Number(line.slice(4));
		else if (line.startsWith("FNH:")) totals.functions.hit += Number(line.slice(4));
	}

	return {
		lines: withPct(totals.lines),
		functions: withPct(totals.functions),
	};
}

function withPct(metric) {
	return {
		...metric,
		pct: metric.found === 0 ? 100 : (metric.hit / metric.found) * 100,
	};
}

function formatPct(value) {
	return `${value.toFixed(2)}%`;
}

function formatMetric(current, base) {
	if (!base) return `${formatPct(current.pct)} (${current.hit}/${current.found})`;
	const delta = current.pct - base.pct;
	const sign = delta > 0 ? "+" : "";
	const indicator = delta < -0.005 ? " 🔻" : delta > 0.005 ? " ✅" : " ➖";
	return `${formatPct(current.pct)} (${current.hit}/${current.found}) — ${sign}${delta.toFixed(2)} pts${indicator}`;
}

function writeOutput(values) {
	const outputPath = process.env.GITHUB_OUTPUT;
	if (!outputPath) return;
	fs.appendFileSync(outputPath, `${Object.entries(values).map(([key, value]) => `${key}=${value}`).join("\n")}\n`);
}

const base = parseLcov(basePath);
const current = parseLcov(currentPath);

if (!current) {
	throw new Error(`Current coverage file not found: ${currentPath}`);
}

const lowered = !!base && (
	current.lines.pct < base.lines.pct - 0.005 ||
	current.functions.pct < base.functions.pct - 0.005
);

const status = !base
	? "⚠️ Base coverage was unavailable, so no regression check was performed."
	: lowered
		? "❌ Coverage decreased compared with the base branch."
		: "✅ Coverage did not decrease compared with the base branch.";

const markdown = `<!-- bun-coverage-report -->
## Bun coverage

${status}

| Metric | Base | Current |
| --- | ---: | ---: |
| Lines | ${base ? formatPct(base.lines.pct) : "n/a"} | ${formatMetric(current.lines, base?.lines)} |
| Functions | ${base ? formatPct(base.functions.pct) : "n/a"} | ${formatMetric(current.functions, base?.functions)} |

<sub>Generated by \`bun test --coverage --coverage-reporter=lcov\`.</sub>
`;

fs.writeFileSync("coverage-comment.md", markdown);

if (process.env.GITHUB_STEP_SUMMARY) {
	fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, markdown);
}

writeOutput({
	lowered,
	line_pct: current.lines.pct.toFixed(2),
	function_pct: current.functions.pct.toFixed(2),
});
